name: Mirror Calico Images to GHCR

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  mirror:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - name: calico/node
            tag: v3.29.0
          - name: calico/pod2daemon-flexvol
            tag: v3.29.0
          - name: calico/typha
            tag: v3.29.0
          - name: calico/csi
            tag: v3.29.0
          - name: calico/node-driver-registrar
            tag: v3.29.0
          - name: calico/kube-controllers
            tag: v3.29.0

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Mirror multi-arch image
        run: |
          SRC_IMAGE=docker.io/${{ matrix.image.name }}:${{ matrix.image.tag }}
          DEST_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:${{ matrix.image.tag }}

          echo "Mirroring $SRC_IMAGE -> $DEST_IMAGE (multi-arch)"
          docker buildx imagetools create \
            --tag $DEST_IMAGE \
            $SRC_IMAGE
